services:
  - type: web
    name: dps-event-notifier
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DPS_USERNAME
        sync: false
      - key: DPS_PASSWORD
        sync: false  
      - key: GMAIL_EMAIL
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false